services:
  - type: web
    name: plateforme-alfa-api
    env: java
    region: frankfurt
    plan: free
    buildCommand: cd backend && mvn clean package -DskipTests
    startCommand: java -Dspring.profiles.active=prod -jar backend/target/bacprep-backend-1.0.0.jar
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: DATABASE_URL
        fromDatabase:
          name: plateforme-alfa-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: FRONTEND_URL
        value: https://plateforme-alfa.vercel.app

databases:
  - name: plateforme-alfa-db
    databaseName: bacprep
    user: bacprep_user
    plan: free
    region: frankfurt